import { Cadre, RT, RW } from './cadre';

const rt001cadre: Cadre[] = [
  {
    name: 'Ahmad Hidayat',
    age: 35,
    phone: '081234567890',
    address: 'Jl. Merdeka No. 1',
    status: 'active',
    wageStatus: 'paid',
    inspection: [
      {
        date: '2024-01-01',
        resident: 'Budi Santoso',
        address: 'Jl. Merdeka No. 1',
        larvaeSpots: 10,
        dfCase: true,
        socialAssistance: true,
      },
      {
        date: '2024-01-02',
        resident: 'Siti Rahayu',
        address: 'Jl. Merdeka No. 2',
        larvaeSpots: 5,
        dfCase: false,
        socialAssistance: false,
      },
      {
        date: '2024-01-03',
        resident: 'Ahmad Hidayat',
        address: 'Jl. Merdeka No. 3',
        larvaeSpots: 2,
        dfCase: true,
        socialAssistance: false,
      },
    ],
  },
  {
    name: 'Siti Rahayu',
    age: 28,
    phone: '081234567891',
    address: 'Jl. Merdeka No. 2',
    status: 'active',
    wageStatus: 'unpaid',
    inspection: [
      {
        date: '2024-01-01',
        resident: 'Rudi Hartono',
        address: 'Jl. Merdeka No. 4',
        larvaeSpots: 15,
        dfCase: true,
        socialAssistance: true,
      },
      {
        date: '2024-01-02',
        resident: 'Lina Wijaya',
        address: 'Jl. Merdeka No. 5',
        larvaeSpots: 0,
        dfCase: false,
        socialAssistance: false,
      },
      {
        date: '2024-01-03',
        resident: 'Dedi Kurniawan',
        address: 'Jl. Merdeka No. 6',
        larvaeSpots: 8,
        dfCase: false,
        socialAssistance: true,
      },
    ],
  },
];

const rt002cadre: Cadre[] = [
  {
    name: 'Budi Santoso',
    age: 40,
    phone: '081234567892',
    address: 'Jl. Veteran No. 1',
    status: 'active',
    wageStatus: 'paid',
    inspection: [
      {
        date: '2024-01-01',
        resident: 'Yuni Astuti',
        address: 'Jl. Veteran No. 4',
        larvaeSpots: 3,
        dfCase: false,
        socialAssistance: false,
      },
      {
        date: '2024-01-02',
        resident: 'Hendra Pratama',
        address: 'Jl. Veteran No. 5',
        larvaeSpots: 12,
        dfCase: true,
        socialAssistance: true,
      },
      {
        date: '2024-01-03',
        resident: 'Siti Aminah',
        address: 'Jl. Veteran No. 6',
        larvaeSpots: 7,
        dfCase: true,
        socialAssistance: true,
      },
    ],
  },
  {
    name: 'Dewi Kusuma',
    age: 32,
    phone: '081234567893',
    address: 'Jl. Veteran No. 2',
    status: 'active',
    wageStatus: 'paid',
    inspection: [
      {
        date: '2024-01-01',
        resident: 'Bambang Sutrisno',
        address: 'Jl. Veteran No. 7',
        larvaeSpots: 20,
        dfCase: true,
        socialAssistance: true,
      },
      {
        date: '2024-01-02',
        resident: 'Rina Wulandari',
        address: 'Jl. Veteran No. 8',
        larvaeSpots: 1,
        dfCase: false,
        socialAssistance: false,
      },
      {
        date: '2024-01-03',
        resident: 'Joko Susilo',
        address: 'Jl. Veteran No. 9',
        larvaeSpots: 6,
        dfCase: false,
        socialAssistance: true,
      },
    ],
  },
];

const rw001rtData: RT[] = [
  {
    rt: '001',
    riskLevel: 'safe',
    homeReports: 8,
    socialAssistance: '2',
    cadres: rt001cadre,
  },
  {
    rt: '002',
    riskLevel: 'alert',
    homeReports: 6,
    socialAssistance: '2',
    cadres: rt002cadre,
  },
];

export const rwData: RW[] = [
  {
    rw: '001',
    pic: 'Budi Santoso',
    homeReports: 14,
    riskLevel: 'safe',
    socialAssistance: '4',
    rtData: rw001rtData,
  },
  {
    rw: '002',
    pic: 'Siti Rahayu',
    homeReports: 8,
    riskLevel: 'alert',
    socialAssistance: '2',
  },
  {
    rw: '003',
    pic: 'Ahmad Hidayat',
    homeReports: 20,
    riskLevel: 'danger',
    socialAssistance: '6',
  },
  {
    rw: '004',
    pic: 'Dewi Kusuma',
    homeReports: 5,
    riskLevel: 'standby',
    socialAssistance: '1',
  },
  {
    rw: '005',
    pic: 'Agus Setiawan',
    homeReports: 25,
    riskLevel: 'critical',
    socialAssistance: '8',
  },
  {
    rw: '006',
    pic: 'Rina Wulandari',
    homeReports: 12,
    riskLevel: 'safe',
    socialAssistance: '3',
  },
  {
    rw: '007',
    pic: 'Joko Susilo',
    homeReports: 18,
    riskLevel: 'alert',
    socialAssistance: '5',
  },
  {
    rw: '008',
    pic: 'Maya Fitriani',
    homeReports: 7,
    riskLevel: 'standby',
    socialAssistance: '2',
  },
  {
    rw: '009',
    pic: 'Rudi Hartono',
    homeReports: 22,
    riskLevel: 'danger',
    socialAssistance: '7',
  },
  {
    rw: '010',
    pic: 'Lina Wijaya',
    homeReports: 3,
    riskLevel: 'safe',
    socialAssistance: '1',
  },
  {
    rw: '011',
    pic: 'Dedi Kurniawan',
    homeReports: 16,
    riskLevel: 'alert',
    socialAssistance: '4',
  },
  {
    rw: '012',
    pic: 'Yuni Astuti',
    homeReports: 9,
    riskLevel: 'standby',
    socialAssistance: '2',
  },
  {
    rw: '013',
    pic: 'Hendra Pratama',
    homeReports: 24,
    riskLevel: 'critical',
    socialAssistance: '9',
  },
  {
    rw: '014',
    pic: 'Siti Aminah',
    homeReports: 6,
    riskLevel: 'safe',
    socialAssistance: '2',
  },
  {
    rw: '015',
    pic: 'Bambang Sutrisno',
    homeReports: 19,
    riskLevel: 'danger',
    socialAssistance: '6',
  },
];
